# Generated by Django 4.2.4 on 2023-09-29 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1024)),
                ('due_date', models.DateTimeField(blank=True)),
                ('assignee', models.CharField(max_length=1024)),
                ('created_by', models.CharField(max_length=1024)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
